keller_tasks = ['Acid',
 'Ammonia',
 'Bakery',
 'Burnt',
 'Chemical',
 'Cold',
 'Decayed',
 'Familiarity',
 'Fishy',
 'Floral',
 'Fruity',
 'Garlic',
 'Grass',
 'Intensity',
 'Musky',
 'Pleasantness',
 'Sour',
 'Spicy',
 'Sweaty',
 'Sweet',
 'Warm',
 'Wood']

sagar_tasks = ['Intensity',
 'Pleasantness',
 'Fishy',
 'Burnt',
 'Sour',
 'Decayed',
 'Musky',
 'Fruity',
 'Sweaty',
 'Cool',
 'Floral',
 'Sweet',
 'Warm',
 'Bakery',
 'Spicy']

dravinsk_tasks = ['FRUITY,CITRUS',
 'LEMON',
 'GRAPEFRUIT',
 'ORANGE',
 'FRUITY,OTHER THAN CITRUS',
 'PINEAPPLE',
 'GRAPE JUICE',
 'STRAWBERRY',
 'APPLE, FRUIT',
 'PEAR',
 'CANTALOUPE, HONEYDEW MELON',
 'PEACH FRUIT',
 'BANANA',
 'FLORAL',
 'ROSE',
 'VIOLETS',
 'LAVENDER',
 'COLOGNE',
 'MUSK',
 'PERFUMERY',
 'FRAGRANT',
 'AROMATIC',
 'HONEY',
 'CHERRY, BERRY',
 'ALMOND',
 'NAIL POLISH REMOVER',
 'NUTTY, WALNUT ETC.',
 'SPICY',
 'CLOVE',
 'CINNAMON',
 'LAUREL LEAVES',
 'TEA LEAVES',
 'SEASONING FOR MEAT',
 'BLACK PEPPER',
 'GREEN PEPPER',
 'DILL',
 'CARAWAY',
 'OAK WOOD,COGNAC',
 'WOODY, RESINOUS',
 'CEDARWOOD',
 'MOTHBALLS',
 'MINTY, PEPPERMINT',
 'CAMPHOR',
 'EUCALYPTUS',
 'CHOCOLATE',
 'VANILLA',
 'SWEET',
 'MAPLE SYRUP',
 'CARAMEL',
 'MALTY',
 'RAISINS',
 'MOLASSES',
 'COCONUT',
 'ANISE, LICORICE',
 'ALCOHOLIC',
 'ETHERISH, ANAESTHETIC',
 'CLEANING FLUID',
 'GASOLINE, SOLVENT',
 'TURPENTINE, PINE OIL',
 'GERANIUM LEAVES',
 'CELERY',
 'FRESH GREEN VEGETABLES',
 'CRUSHED WEEDS',
 'CRUSHED GRASS',
 'HERBAL, GREEN,CUTGRASS',
 'RAW CUCUMBER',
 'HAY',
 'GRAINY (AS GRAIN)',
 'YEASTY',
 'BAKERY (FRESH BREAD)',
 'SOUR MILK',
 'FERMENTED, ROTTEN FRUIT',
 'BEERY',
 'SOAPY',
 'LEATHER',
 'CARDBOARD',
 'ROPE',
 'WET PAPER',
 'WET WOOL,WET DOG',
 'DIRTY LINEN',
 'STALE',
 'MUSTY, EARTHY, MOLDY',
 'RAW POTATO',
 'MOUSE',
 'MUSHROOM',
 'PEANUT BUTTER',
 'BEANY',
 'EGGY, FRESH EGGS',
 'BARK,BIRCHBARK',
 'CORK',
 'BURNT,SMOKY',
 'FRESH TOBACCO SMOKE',
 'INCENSE',
 'COFFEE',
 'STALE TOBACCO SMOKE',
 'BURNT PAPER',
 'BURNT MILK',
 'BURNT RUBBER',
 'TAR',
 'CREOSOTE',
 'DISINFECTANT, CARBOLIC',
 'MEDICINAL',
 'CHEMICAL',
 'BITTER',
 'SHARP, PUNGENT, ACID',
 'SOUR, VINEGAR',
 'SAUERKRAUT',
 'AMMONIA',
 'URINE',
 'CAT URINE',
 'FISHY',
 'KIPPERY,SMOKED FISH',
 'SEMINAL, SPERM-LIKE',
 'NEW RUBBER',
 'SOOTY',
 'BURNT CANDLE',
 'KEROSENE',
 'OILY, FATTY',
 'BUTTERY, FRESH BUTTER',
 'PAINT',
 'VARNISH',
 'POPCORN',
 'FRIED CHICKEN',
 'MEATY ( COOKED,GOOD)',
 'SOUPY',
 'COOKED VEGETABLES',
 'RANCID',
 'SWEATY',
 'CHEESY',
 'HOUSEHOLD GAS',
 'SULFIDIC',
 'GARLIC, ONION',
 'METALLIC',
 'BLOOD, RAW MEAT',
 'ANIMAL',
 'SEWER',
 'PUTRID, FOUL, DECAYED',
 'FECAL, LIKE MANURE',
 'CADAVEROUS',
 'SICKENING',
 'DRY, POWDERY',
 'CHALKY',
 'LIGHT',
 'HEAVY',
 'COOL,COOLING',
 'WARM']


#generate an array with the common tasks
common_tasks = list(set(keller_tasks).intersection(sagar_tasks))

#make an array for each of sagar and keller and put 1 if the task is common and 0 if not
keller_array = [1 if task in common_tasks else 0 for task in keller_tasks]
sagar_array = [1 if task in common_tasks else 0 for task in sagar_tasks]


